# Generated by Django 4.0.8 on 2023-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imag', models.ImageField(upload_to='image/%Y')),
                ('description', models.TextField(blank=True)),
                ('date_publ', models.DateField(verbose_name='Дата выхода')),
            ],
        ),
    ]
